name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint

    - name: Run Tests
      run: npm test

    - name: Build Docker Image
      run: docker build -t nodejs-app:latest .

    - name: Save Docker Image to tar
      run: docker save nodejs-app:latest -o app.tar

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

    - name: Copy Docker Image to Remote Server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "app.tar"
        target: "/home/vagrant/app.tar"
        port: 22

    - name: Load and Restart Container on Remote Server
      run: |
        ssh -i ~/.ssh/id_rsa vagrant@${{ secrets.REMOTE_HOST }} << 'EOF'
        docker load -i /home/vagrant/app.tar
        cd /home/vagrant/app
        docker compose down
        docker compose up -d --build
        EOF
