name: Node.js CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Lint Code
      run: |
        npm install --save-dev eslint
        npx eslint . || true

    - name: Build Docker Image
      run: |
        docker build -t nodejs-cicd-pipeline .

    - name: Save Docker Image to TAR
      run: docker save nodejs-cicd-pipeline -o app.tar

    - name: Copy Image to App Server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_KEY }}
        source: "./app.tar"
        target: "/home/vagrant/"

    - name: Deploy on App Server via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_KEY }}
        script: |
          docker load -i app.tar
          docker stop app || true && docker rm app || true
          docker run -d --name app -p 3000:3000 nodejs-cicd-pipeline
