name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - run: npm ci
    - run: npm test

  build-and-deploy:
    needs: test
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build Docker image
      run: docker build -t nodejs-cicd-app .
    - name: Save container image
      run: docker save nodejs-cicd-app -o app.tar
    - name: Copy image to app server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.APP_SERVER_IP }}
        username: vagrant
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "app.tar"
        target: "/home/vagrant"
    - name: Deploy on App Server
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa vagrant@${{ secrets.APP_SERVER_IP }} "
          docker load -i /home/vagrant/app.tar &&
          docker compose -f /home/vagrant/docker-compose.yml up -d --build
        "
